lib/homepage_web/router.ex
defmodule HomepageWeb.Router do
  use HomepageWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HomepageWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HomepageWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HomepageWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/posts", PostController, [:index, :show, :new, :create, :delete]
    resources "/events", EventController, only: [:new, :create, :delete]
    get "/login", SessionController, :new
    resources "/sessions", SessionController, only: [:create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", HomepageWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HomepageWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/homepage_web/views/layout_view.ex
defmodule HomepageWeb.LayoutView do
  use HomepageWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/homepage_web/templates/layout/app.html.heex
<main class="pl-5 pr-5 pt-3 pb-3">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/homepage_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/homepage_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>  
  <meta name="csrf-token" content={csrf_token_value()}>
  <%= live_title_tag assigns[:page_title] || "Josh Felton Mathews" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css" )} />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js" )}></script>
    <script>
      function toggleMenuMobile() {
        const menu = document.getElementById("main-menu");
        if (menu.classList.contains("hidden")) {
          menu.classList.remove("hidden")
          return;
        }
        menu.classList.add("hidden")
      }
    </script>
</head>

<body class="bg-gray-800">
  <header>
    <nav class="flex items-center justify-between flex-wrap p-6">
      <div class="flex items-center flex-shrink-0 text-orange-200 mr-6">
        <a href="/" class="font-semibold text-xl tracking-tight">Josh Felton Mathews</a>
      </div>
      <div class="block lg:hidden">
        <button onclick="toggleMenuMobile()"
          class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
          <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>Menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
          </svg>
        </button>
      </div>
      <div id="main-menu" class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
          <a href="https://music.joshfeltonmathews.com" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
            Musician
          </a>

          <a href="https://github.com/jfacoustic" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
            Software Engineer
          </a>

          <a href="/posts" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
            Blog
          </a>
        </div>
        <div class="lg:content-end block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
          <%= if @authenticated do %>
            <%= link "Log out" , to: Routes.session_path(@conn, :delete, 0), method: "delete" ,
              class: "lg:content-end block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white" %>
              <% end %>
        </div>
      </div>
    </nav>
  </header>
  <%= @inner_content %>
</body>

</html>