lib/homepage_web/router.ex
defmodule HomepageWeb.Router do
  use HomepageWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HomepageWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HomepageWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HomepageWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/posts", PostController, [:index, :show, :new, :create, :delete]
    resources "/events", EventController, only: [:new, :create, :delete]
    get "/login", SessionController, :new
    resources "/sessions", SessionController, only: [:create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", HomepageWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HomepageWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/homepage_web/templates/page/index.html.heex
<div class="grid lg:grid-cols-4">
  <div class="prose lg:col-span-3">
    <h1 class="text-orange-300">Bienvenue!</h1>
    <h3 class="text-white">Josh Felton Mathews is a passionate musician, software engineer, and outdoorsman.
        He has a diverse repertoire, singing in French, Spanish, German, and Chinese and covering a wide range of genres, including folk, country, and soft rock.
    </h3>
    <p class="text-white">When he's not performing, Josh is a professional software developer who specializes in Flutter, a mobile app development framework.
                          He currently works at Emporia Energy, a company that is revolutionizing home energy, helping homeowners manage and reduce their energy usage.
                          He regularly contributes to open source software and cofounded The Leage of Dedicated Programmers, a computer science club in Grand Junction, CO.
                          </p>
    <p class="text-white">In addition to his work in music and programming, Josh is also an avid mountaineer.
                          He loves to explore new peaks and push himself to his limits. He has climbed several of Colorado’s fourteeners and is building his skills in multi-pitch trad climbing.
                          He also skis and mountain-bikes.</p>
    <p class="text-white">He is also a committed volunteer at the Cavalcade, a non-profit music venue in Fruita, Colorado.
                          He has volunteered for over ten years, dedicating his energy to supporting the local music scene.</p>
    <p class="text-white">With his diverse set of skills and interests, Josh is a true renaissance man.
                          Whether he's performing on stage, developing software, or climbing mountains, he approaches everything he does with passion and dedication.</p>
  </div>
  <div class="border border-solid border-teal-200 bg-color p-5 col-span-1 h-80 prose">
    <h1 class="text-orange-300">
      Events
    </h1>
    <%= if @authenticated do %>
      <%= link "Add event", to: Routes.event_path(@conn, :new), method: "get", class: "text-white"%>
    <% end %>
    <%= for event <- @events do %>
      <div>
        <%= link "#{event.location} on #{event.datetime}", to: event.link, class: "text-white" %>
        <%= if @authenticated do %>
          <%= link "Delete event", to: Routes.event_path(@conn, :delete, event.id), method: "delete" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>